// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	"github.com/bbdLe/iGame/comm"
	"github.com/bbdLe/iGame/comm/codec"
	_ "github.com/bbdLe/iGame/comm/codec/gogopb"
	"github.com/bbdLe/iGame/comm/util"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	"reflect"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CsMsgId int32

const (
	CsMsgId_CS_CMD_START     CsMsgId = 0
	CsMsgId_CS_CMD_LOGIN_REQ CsMsgId = 1
	CsMsgId_CS_CMD_LOGIN_RES CsMsgId = 2
	CsMsgId_CS_CMD_CHAT_REQ  CsMsgId = 3
	CsMsgId_CS_CMD_CHAT_RES  CsMsgId = 4
)

var CsMsgId_name = map[int32]string{
	0: "CS_CMD_START",
	1: "CS_CMD_LOGIN_REQ",
	2: "CS_CMD_LOGIN_RES",
	3: "CS_CMD_CHAT_REQ",
	4: "CS_CMD_CHAT_RES",
}

var CsMsgId_value = map[string]int32{
	"CS_CMD_START":     0,
	"CS_CMD_LOGIN_REQ": 1,
	"CS_CMD_LOGIN_RES": 2,
	"CS_CMD_CHAT_REQ":  3,
	"CS_CMD_CHAT_RES":  4,
}

func (x CsMsgId) String() string {
	return proto.EnumName(CsMsgId_name, int32(x))
}

func (CsMsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type LoginReq struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type LoginRes struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ServerId             int32    `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}
func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRes) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type ChatReq struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatReq) Reset()         { *m = ChatReq{} }
func (m *ChatReq) String() string { return proto.CompactTextString(m) }
func (*ChatReq) ProtoMessage()    {}
func (*ChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}
func (m *ChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatReq.Unmarshal(m, b)
}
func (m *ChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatReq.Marshal(b, m, deterministic)
}
func (m *ChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatReq.Merge(m, src)
}
func (m *ChatReq) XXX_Size() int {
	return xxx_messageInfo_ChatReq.Size(m)
}
func (m *ChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatReq proto.InternalMessageInfo

func (m *ChatReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ChatRes struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRes) Reset()         { *m = ChatRes{} }
func (m *ChatRes) String() string { return proto.CompactTextString(m) }
func (*ChatRes) ProtoMessage()    {}
func (*ChatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}
func (m *ChatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRes.Unmarshal(m, b)
}
func (m *ChatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRes.Marshal(b, m, deterministic)
}
func (m *ChatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRes.Merge(m, src)
}
func (m *ChatRes) XXX_Size() int {
	return xxx_messageInfo_ChatRes.Size(m)
}
func (m *ChatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRes proto.InternalMessageInfo

func (m *ChatRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ChatRes) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.CsMsgId", CsMsgId_name, CsMsgId_value)
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "proto.LoginRes")
	proto.RegisterType((*ChatReq)(nil), "proto.ChatReq")
	proto.RegisterType((*ChatRes)(nil), "proto.ChatRes")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xdd, 0x6a, 0xd7, 0xf6, 0x21, 0x18, 0x9e, 0x43, 0x8a, 0x43, 0x90, 0x9e, 0xc4, 0x83,
	0x17, 0x6f, 0xde, 0x46, 0x14, 0x2d, 0x6c, 0x8a, 0x69, 0x3d, 0x97, 0x49, 0x63, 0x2d, 0xae, 0xcd,
	0x96, 0x97, 0xed, 0xef, 0x97, 0x64, 0xd9, 0x2e, 0xf3, 0xd4, 0xf7, 0xfd, 0xbe, 0xf2, 0xcb, 0x4b,
	0x20, 0xe9, 0xa8, 0xb9, 0x5f, 0x69, 0x65, 0x14, 0x86, 0xee, 0x93, 0x09, 0x88, 0x67, 0xaa, 0x69,
	0x7b, 0x21, 0xd7, 0x98, 0x42, 0xb4, 0x95, 0x9a, 0x5a, 0xd5, 0xa7, 0x83, 0x9b, 0xc1, 0x6d, 0x22,
	0xf6, 0x11, 0xaf, 0x20, 0x5e, 0x2d, 0x17, 0xe6, 0x5b, 0xe9, 0x2e, 0x1d, 0xba, 0xea, 0x90, 0x91,
	0x41, 0xb0, 0x69, 0xeb, 0x34, 0x70, 0xd8, 0x8e, 0xd9, 0xe7, 0xc1, 0x49, 0x78, 0x09, 0x23, 0x2d,
	0x69, 0xb3, 0x34, 0x4e, 0x19, 0x0a, 0x9f, 0x70, 0x0c, 0xa1, 0x51, 0xbf, 0xb2, 0xf7, 0xba, 0x5d,
	0xc0, 0x09, 0x24, 0x24, 0xf5, 0x56, 0xea, 0xca, 0x1b, 0x43, 0x11, 0xef, 0x40, 0x5e, 0x67, 0x13,
	0x88, 0xf8, 0xcf, 0xc2, 0xd8, 0x4d, 0x19, 0x04, 0x1d, 0x35, 0x7e, 0x4b, 0x3b, 0x66, 0x8f, 0xfb,
	0x92, 0x8e, 0x4b, 0xbc, 0x06, 0x20, 0x49, 0xf6, 0x26, 0xd6, 0x6b, 0x4f, 0x0c, 0x44, 0xe2, 0x49,
	0x5e, 0xdf, 0xad, 0x21, 0xe2, 0x34, 0xa7, 0x26, 0xaf, 0x91, 0xc1, 0x19, 0x2f, 0x2a, 0x3e, 0x7f,
	0xaa, 0x8a, 0x72, 0x2a, 0x4a, 0x76, 0x82, 0x63, 0x60, 0x9e, 0xcc, 0xde, 0x5f, 0xf2, 0xb7, 0x4a,
	0x3c, 0x7f, 0xb0, 0xc1, 0x3f, 0xb4, 0x60, 0x43, 0xbc, 0x80, 0x73, 0x4f, 0xf9, 0xeb, 0xb4, 0x74,
	0xbf, 0x06, 0xc7, 0xb0, 0x60, 0xa7, 0x5f, 0x23, 0xf7, 0xfa, 0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x07, 0xd3, 0xe5, 0x6e, 0x91, 0x01, 0x00, 0x00,
}

func init() {

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(util.StringHash("proto.LoginReq")),
		Type:  reflect.TypeOf((*LoginReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(util.StringHash("proto.LoginRes")),
		Type:  reflect.TypeOf((*LoginRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(util.StringHash("proto.ChatReq")),
		Type:  reflect.TypeOf((*ChatReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(util.StringHash("proto.ChatRes")),
		Type:  reflect.TypeOf((*ChatRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

}
